### ISSUE TITLE
プロジェクトが読み込めませんでした。

### ISSUE THREAD

**Issue by LyricalMaestro** [NikoYuwono/realm-browser-android#1]
Qiitaの記事にもコメントさせていただいたものです。
http://qiita.com/NikoYuwono/items/97968905bfa2ae08beac#comment-003cf8358cc84a374dfc

このコードをこちらの環境でうごかしてみようと思いgitからfork、その後手元のAndroidStudioでgradleプロジェクトとして開こうとしたら以下のようなエラーが発生してうまく読み込めませんでした。

Gradle 'realm-browser-android' project refresh failed
Error:Configuration with name 'default' not found.

**Comment by NikoYuwono** [comment]
@LyricalMaestro realmbrowserモジュールのgradleファイルをアップロードしました。もう一度試してみてください。宜しくお願いします。

**Comment by LyricalMaestro** [comment]
最新版を適用して動かしてみたら無事にうまくいきました。ありがとうございます。
